### ISSUE TITLE
Properly keep p.constructor == Point

### ISSUE THREAD

**Issue by deanm** [mapbox/point-geometry#11]
For the default prototype on a function you have f.prototype.constructor = f.  However, in this code the entire prototype is reassigned to an object literal:

https://github.com/mapbox/point-geometry/blob/9090b2cdbe69f237bc043154879ace6a01b772e2/index.js#L22

This means:

```
new Point(1, 1).constructor === Point
false

new Point(1, 1).constructor === { }.constructor
true
```

It should be enough to add a `constructor: Point` into the object literal.

**Comment by mourner** [comment]
Fixed in https://github.com/mapbox/point-geometry/commit/1d80440aa24c3e7d24f253e9d47fc40c3ef8a078
